import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import { StyleSwitcher } from "@/components/style-switcher";
import { ThemeProvider } from "@/components/theme-provider";
import SiteHeader from "./SiteHeader";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const clash = localFont({
  src: "./ClashDisplay-Semibold.otf",
  variable: "--font-clash",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("font-sans", inter.variable, clash.variable)}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <div className="container">
            <SiteHeader />
            <div>{children}</div>
          </div>
        </ThemeProvider>
        <StyleSwitcher />
      </body>
    </html>
  );
}
